# Generated by Django 5.0.4 on 2024-04-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimp',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
    ]
