# Generated by Django 5.0.4 on 2024-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='is_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shrimp',
            name='is_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shrimp',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='algae',
            field=models.ManyToManyField(blank=True, to='fish.algae'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='fish',
            field=models.ManyToManyField(blank=True, to='fish.fish'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='shrimp',
            field=models.ManyToManyField(blank=True, to='fish.shrimp'),
        ),
    ]
