# Generated by Django 5.0.4 on 2024-04-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_shrimp_is_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='algae',
            name='is_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='algae',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
    ]
